import type { Brand, BrandCategory } from './brand.types'

/**
 * In-memory sample data. Shapes match exactly what the future Spring Boot API
 * is expected to return, so swapping the service implementation is transparent.
 */
export const mockCategories: BrandCategory[] = [
  { id: 'c1', name: 'Streetwear', slug: 'streetwear', description: 'Bold, culture-driven everyday fashion.', brandCount: 3 },
  { id: 'c2', name: 'Minimalist', slug: 'minimalist', description: 'Clean lines and considered basics.', brandCount: 2 },
  { id: 'c3', name: 'Sustainable', slug: 'sustainable', description: 'Low-impact materials and ethical supply chains.', brandCount: 2 },
  { id: 'c4', name: 'Athleisure', slug: 'athleisure', description: 'Performance wear built for real life.', brandCount: 1 },
  { id: 'c5', name: 'Luxury', slug: 'luxury', description: 'Exclusive, high-end fashion and craftsmanship.', brandCount: 2 },
  { id: 'c6', name: 'Vintage', slug: 'vintage', description: 'Curated secondhand and heritage pieces.', brandCount: 1 },
]

/** Tag for editorial picks — use this to mark brands featured in editor selection */
export const editorPickTag = '__editor_pick__'

export const mockBrands: Brand[] = [
  {
    id: 'b1',
    name: 'Northwind',
    slug: 'northwind',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Northwind',
    description: 'Technical outerwear with a minimalist edge, made for the city and the trail.',
    category: 'minimalist',
    country: 'Sweden',
    websiteUrl: 'https://example.com/northwind',
    rating: 4.7,
    reviewsCount: 12840,
    popularity: 88,
    sustainabilityScore: 82,
    trustScore: 91,
    priceRange: 'premium',
    tags: ['outerwear', 'unisex', 'recycled', editorPickTag],
    featured: true,
  },
  {
    id: 'b2',
    name: 'Halcyon',
    slug: 'halcyon',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Halcyon',
    description: 'Considered basics in organic cotton — the wardrobe you reach for daily.',
    category: 'minimalist',
    country: 'Japan',
    websiteUrl: 'https://example.com/halcyon',
    rating: 4.5,
    reviewsCount: 8210,
    popularity: 76,
    sustainabilityScore: 90,
    trustScore: 88,
    priceRange: 'mid',
    tags: ['basics', 'organic', 'everyday', editorPickTag],
    featured: true,
  },
  {
    id: 'b3',
    name: 'Riot Society',
    slug: 'riot-society',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Riot',
    description: 'Graphic-led streetwear born from skate and music subcultures.',
    category: 'streetwear',
    country: 'USA',
    websiteUrl: 'https://example.com/riot-society',
    rating: 4.2,
    reviewsCount: 15320,
    popularity: 93,
    sustainabilityScore: 54,
    trustScore: 79,
    priceRange: 'budget',
    tags: ['graphic', 'skate', 'street'],
    featured: true,
  },
  {
    id: 'b4',
    name: 'Terra & Thread',
    slug: 'terra-and-thread',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Terra',
    description: 'Regeneratively farmed fibres and full supply-chain transparency.',
    category: 'sustainable',
    country: 'India',
    websiteUrl: 'https://example.com/terra-thread',
    rating: 4.8,
    reviewsCount: 6420,
    popularity: 71,
    sustainabilityScore: 97,
    trustScore: 94,
    priceRange: 'premium',
    tags: ['regenerative', 'transparent', 'ethical', editorPickTag],
    featured: true,
  },
  {
    id: 'b5',
    name: 'Atelier Nord',
    slug: 'atelier-nord',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=AtelierNord',
    description: 'Elevated streetwear with a luxury finish and limited drops.',
    category: 'streetwear',
    country: 'France',
    websiteUrl: 'https://example.com/member-off',
    rating: 4.4,
    reviewsCount: 9870,
    popularity: 85,
    sustainabilityScore: 61,
    trustScore: 83,
    priceRange: 'luxury',
    tags: ['limited', 'elevated', 'drops'],
    featured: false,
  },
  {
    id: 'b6',
    name: 'Kinetic',
    slug: 'kinetic',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Kinetic',
    description: 'Performance athleisure engineered to move from gym to street.',
    category: 'athleisure',
    country: 'UK',
    websiteUrl: 'https://example.com/kinetic',
    rating: 4.3,
    reviewsCount: 11250,
    popularity: 80,
    sustainabilityScore: 68,
    trustScore: 82,
    priceRange: 'mid',
    tags: ['performance', 'active', 'stretch', editorPickTag],
    featured: false,
  },
  {
    id: 'b7',
    name: 'Cedarline',
    slug: 'cedarline',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=Cedarline',
    description: 'Heritage-inspired staples in deadstock and low-impact fabrics.',
    category: 'sustainable',
    country: 'Canada',
    websiteUrl: 'https://example.com/cedarline',
    rating: 4.6,
    reviewsCount: 5310,
    popularity: 64,
    sustainabilityScore: 89,
    trustScore: 90,
    priceRange: 'premium',
    tags: ['heritage', 'deadstock', 'low-impact'],
    featured: false,
  },
  {
    id: 'b8',
    name: 'Void Theory',
    slug: 'void-theory',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=VoidTheory',
    description: 'Monochrome streetwear silhouettes with an architectural sensibility.',
    category: 'streetwear',
    country: 'Germany',
    websiteUrl: 'https://example.com/void-theory',
    rating: 4.1,
    reviewsCount: 7180,
    popularity: 74,
    sustainabilityScore: 58,
    trustScore: 77,
    priceRange: 'mid',
    tags: ['monochrome', 'architectural', 'street'],
    featured: false,
  },
  {
    id: 'b9',
    name: 'Apex Collective',
    slug: 'apex-collective',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=ApexCollective',
    description: 'Contemporary luxury menswear merging tailoring with street culture.',
    category: 'luxury',
    country: 'Italy',
    websiteUrl: 'https://example.com/apex',
    rating: 4.6,
    reviewsCount: 4920,
    popularity: 72,
    sustainabilityScore: 65,
    trustScore: 89,
    priceRange: 'luxury',
    tags: ['menswear', 'tailored', 'contemporary'],
    featured: false,
  },
  {
    id: 'b10',
    name: 'Revive Vintage',
    slug: 'revive-vintage',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=ReviveVintage',
    description: 'Carefully curated vintage and secondhand collections with a modern eye.',
    category: 'vintage',
    country: 'USA',
    websiteUrl: 'https://example.com/revive',
    rating: 4.4,
    reviewsCount: 3870,
    popularity: 68,
    sustainabilityScore: 95,
    trustScore: 86,
    priceRange: 'budget',
    tags: ['vintage', 'secondhand', 'curated'],
    featured: false,
  },
  {
    id: 'b11',
    name: 'Echo Studios',
    slug: 'echo-studios',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=EchoStudios',
    description: 'Artist-collaborative prints and limited edition apparel drops.',
    category: 'streetwear',
    country: 'Spain',
    websiteUrl: 'https://example.com/echo',
    rating: 4.3,
    reviewsCount: 5680,
    popularity: 79,
    sustainabilityScore: 72,
    trustScore: 81,
    priceRange: 'mid',
    tags: ['artist', 'limited', 'collaborative'],
    featured: false,
  },
  {
    id: 'b12',
    name: 'Lumina Essentials',
    slug: 'lumina-essentials',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=LuminaEssentials',
    description: 'Timeless minimalist basics engineered for simplicity and quality.',
    category: 'minimalist',
    country: 'Switzerland',
    websiteUrl: 'https://example.com/lumina',
    rating: 4.7,
    reviewsCount: 9210,
    popularity: 81,
    sustainabilityScore: 88,
    trustScore: 93,
    priceRange: 'premium',
    tags: ['basics', 'timeless', 'quality'],
    featured: true,
  },
  {
    id: 'b13',
    name: 'Flow Active',
    slug: 'flow-active',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=FlowActive',
    description: 'Sustainable activewear made from recycled ocean plastics.',
    category: 'athleisure',
    country: 'Netherlands',
    websiteUrl: 'https://example.com/flow',
    rating: 4.5,
    reviewsCount: 7450,
    popularity: 82,
    sustainabilityScore: 96,
    trustScore: 90,
    priceRange: 'mid',
    tags: ['activewear', 'sustainable', 'ocean-safe'],
    featured: false,
  },
  {
    id: 'b14',
    name: 'Nova Factory',
    slug: 'nova-factory',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=NovaFactory',
    description: 'Experimental fashion lab pushing boundaries with innovative cuts.',
    category: 'streetwear',
    country: 'Belgium',
    websiteUrl: 'https://example.com/nova',
    rating: 4.2,
    reviewsCount: 4310,
    popularity: 76,
    sustainabilityScore: 69,
    trustScore: 78,
    priceRange: 'premium',
    tags: ['experimental', 'innovative', 'avant-garde'],
    featured: false,
  },
  {
    id: 'b15',
    name: 'Zenith Heritage',
    slug: 'zenith-heritage',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=ZenithHeritage',
    description: 'Legacy brand preserving traditional craftsmanship with modern silhouettes.',
    category: 'luxury',
    country: 'Portugal',
    websiteUrl: 'https://example.com/zenith',
    rating: 4.8,
    reviewsCount: 3210,
    popularity: 62,
    sustainabilityScore: 84,
    trustScore: 96,
    priceRange: 'luxury',
    tags: ['heritage', 'craftsmanship', 'tradition'],
    featured: false,
  },
  {
    id: 'b16',
    name: 'Pulse Metro',
    slug: 'pulse-metro',
    logoUrl: 'https://api.dicebear.com/9.x/initials/svg?seed=PulseMetro',
    description: 'Urban commuter wear optimized for the modern city lifestyle.',
    category: 'athleisure',
    country: 'South Korea',
    websiteUrl: 'https://example.com/pulse',
    rating: 4.4,
    reviewsCount: 8760,
    popularity: 84,
    sustainabilityScore: 77,
    trustScore: 87,
    priceRange: 'mid',
    tags: ['urban', 'commuter', 'functional'],
    featured: false,
  },
]
